import { CargoType } from "@/app/workflow/_feature/types";

// Helper function to format dates
const formatDate = (date) => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const mockData: CargoType[] = [
  {
    id: 1,
    created_at: formatDate(new Date("2024-06-21T10:30:00Z")),
    receipt_address: "ул. Ленина, д. 1, Москва",
    unloading_city: "Москва",
    weight: "1000 кг",
    volume: "10 м³",
    quantity: "500 шт",
    driver: "Иван Иванов",
    amount: "1500 USD",
    is_unpalletizing: true,
    comments: "Осторожно, хрупкое",
    client_name: "ООО Ромашка",
    client_bin: "123456789",
    cargo_name: "Электроника",
    payer: "ООО Ромашка",
    transportation_manager: "Петр Петров",
    is_documents: true,
    status: "В пути",
    arrival_date: formatDate(new Date("2024-06-25T14:00:00Z")),
    sgm_manager: "Сергей Сергеев",
    payment: "Оплачено",
    loading_scheme: "Стандарт",
    user_id: "user123",
  },
  {
    id: 2,
    created_at: formatDate(new Date("2024-06-20T09:15:00Z")),
    receipt_address: "пр. Мира, д. 2, Санкт-Петербург",
    unloading_city: "Санкт-Петербург",
    weight: "1500 кг",
    volume: "15 м³",
    quantity: "300 шт",
    driver: "Алексей Смирнов",
    amount: "2000 USD",
    is_unpalletizing: false,
    comments: "Товары для дома",
    client_name: "ООО Прогресс",
    client_bin: "987654321",
    cargo_name: "Мебель",
    payer: "ООО Прогресс",
    transportation_manager: "Мария Иванова",
    is_documents: false,
    status: "Доставлено",
    arrival_date: formatDate(new Date("2024-06-24T08:00:00Z")),
    sgm_manager: "Ольга Сидорова",
    payment: "Не оплачено",
    loading_scheme: "Индивидуальная",
    user_id: "user456",
  },
  {
    id: 3,
    created_at: formatDate(new Date("2024-06-19T12:45:00Z")),
    receipt_address: "ул. Пушкина, д. 3, Казань",
    unloading_city: "Казань",
    weight: "1200 кг",
    volume: "12 м³",
    quantity: "400 шт",
    driver: "Сергей Петров",
    amount: "1800 USD",
    is_unpalletizing: true,
    comments: "Осторожно, легко бьется",
    client_name: "ООО Вектор",
    client_bin: "456789123",
    cargo_name: "Бытовая техника",
    payer: "ООО Вектор",
    transportation_manager: "Андрей Кузнецов",
    is_documents: true,
    status: "В пути",
    arrival_date: formatDate(new Date("2024-06-23T16:00:00Z")),
    sgm_manager: "Дмитрий Ковалев",
    payment: "Оплачено",
    loading_scheme: "Стандарт",
    user_id: "user789",
  },
  {
    id: 4,
    created_at: formatDate(new Date("2024-06-18T14:30:00Z")),
    receipt_address: "ул. Чехова, д. 4, Новосибирск",
    unloading_city: "Новосибирск",
    weight: "900 кг",
    volume: "9 м³",
    quantity: "250 шт",
    driver: "Максим Максимов",
    amount: "1300 USD",
    is_unpalletizing: false,
    comments: "Сельхозтехника",
    client_name: "ООО Агро",
    client_bin: "321654987",
    cargo_name: "Сельхозоборудование",
    payer: "ООО Агро",
    transportation_manager: "Елена Захарова",
    is_documents: false,
    status: "В пути",
    arrival_date: formatDate(new Date("2024-06-22T10:00:00Z")),
    sgm_manager: "Юрий Жуков",
    payment: "Не оплачено",
    loading_scheme: "Индивидуальная",
    user_id: "user321",
  },
  {
    id: 5,
    created_at: formatDate(new Date("2024-06-17T11:00:00Z")),
    receipt_address: "ул. Гоголя, д. 5, Екатеринбург",
    unloading_city: "Екатеринбург",
    weight: "1100 кг",
    volume: "11 м³",
    quantity: "350 шт",
    driver: "Федор Федоров",
    amount: "1600 USD",
    is_unpalletizing: true,
    comments: "Оборудование для офисов",
    client_name: "ООО Офислайн",
    client_bin: "789123456",
    cargo_name: "Офисная мебель",
    payer: "ООО Офислайн",
    transportation_manager: "Виктория Петрова",
    is_documents: true,
    status: "В пути",
    arrival_date: formatDate(new Date("2024-06-21T12:00:00Z")),
    sgm_manager: "Григорий Орлов",
    payment: "Оплачено",
    loading_scheme: "Стандарт",
    user_id: "user654",
  },
];

export default mockData;
