import { Cargo } from "./types";

const mockData: Cargo[] = [
  {
    id: BigInt(1),
    created_at: new Date("2024-06-21T10:30:00Z"),
    receipt_address: "123 Main St, Springfield",
    unloading_city: "Springfield",
    weight: "1000 kg",
    volume: "10 m³",
    quantity: "500 units",
    driver: "John Doe",
    amount: "1500 USD",
    is_unpalletizing: true,
    comments: "Handle with care",
    client_name: "Acme Corp",
    client_bin: "123456789",
    cargo_name: "Electronics",
    payer: "Acme Corp",
    transportation_manager: "Jane Smith",
    is_documents: true,
    status: "In Transit",
    arrival_date: new Date("2024-06-25T14:00:00"),
    sgm_manager: "Steve Johnson",
    payment: "Paid",
    loading_scheme: "Standard",
    user_id: "user123",
  },
  {
    id: BigInt(2),
    created_at: new Date("2024-06-20T09:15:00Z"),
    receipt_address: "456 Elm St, Shelbyville",
    unloading_city: "Shelbyville",
    weight: "1500 kg",
    volume: "15 m³",
    quantity: "300 units",
    driver: "Alice Johnson",
    amount: "2000 USD",
    is_unpalletizing: false,
    comments: "Fragile items",
    client_name: "Global Inc",
    client_bin: "987654321",
    cargo_name: "Furniture",
    payer: "Global Inc",
    transportation_manager: "Mike Brown",
    is_documents: false,
    status: "Delivered",
    arrival_date: new Date("2024-06-24T08:00:00"),
    sgm_manager: "Sara Davis",
    payment: "Unpaid",
    loading_scheme: "Custom",
    user_id: "user456",
  },
];

export default mockData;
